### ISSUE TITLE
[Problem] bittube-wallet-gui.exe will execute but nothing happens - Windows 10

### ISSUE THREAD

**Issue by teasider** [ipbc-dev/bittube-wallet-gui#10]
The app shows up for a second on the task manager and disappear.

Tried running it as administrator but that doesn't work either.

**Comment by ipbc-dev** [comment]
try runing it in low graphics mode using [this](https://github.com/ipbc-dev/bittube-wallet-gui/blob/master/start-low-graphics-mode.bat) bat file.

**Comment by cadayton** [comment]
I had the same experience, so I aborted the installation and removed the software.
