### ISSUE TITLE
Missing windows dependencies

### ISSUE THREAD

**Issue by taeguscromis** [ipbc-dev/bittube-wallet-gui#12]
If the Windows wallet is missing dependencies like c++ runtime or opengl it simply crashes in case of opengl or give an unfriendly error message. I suggest:

1. The wallet should use a launcher
2. The launcher checks for dependencies, c++ runtime, opengl
3. if c++ runtime is not found the wallet offers an install before launching
4. if opengl is not found it offers an install otherwises it flags itself to use QT

![unknown](https://user-images.githubusercontent.com/40831804/42280973-885d8344-7fa2-11e8-85ad-0497561ece2a.png)

**Comment by sabotagebeats** [comment]
I have same issue missing QT DLL's

**Comment by italocoin-project** [comment]
Should be Resolved by now, download latest version and let me know.
