### ISSUE TITLE
The miner starts itself even if the wallet fails to start

### ISSUE THREAD

**Issue by taeguscromis** [ipbc-dev/bittube-wallet-gui#13]
At first wallet launch on a fresh windows system the wallet failed to start due to missing dependencies. It lacked:

- c++ runtime
- opengl

After installing c++ runtime the wallet silently crashes at start but the miner however start without anyone starting it. after starting the wallet without opengl the miner still starts and cannot be stopped from the wallet as the button is grayed out. Killing the miner only reastarts it.

![unknown 1](https://user-images.githubusercontent.com/40831804/42281181-0d5ac840-7fa3-11e8-8c35-cc0a72ba1dd6.png)

**Comment by italocoin-project** [comment]
Try the latest release, let me know if you get the same issue
