### ISSUE TITLE
Mac wallet won't launch

### ISSUE THREAD

**Issue by sthewissen** [ipbc-dev/bittube-wallet-gui#18]
My Mac wallet (2.0.0.2) also doesn't open, but when I open the Mac wallet I get:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/bittube-wallet-gui.app.
```

Opening 2.0.0.1 does work.

**Comment by ipbc-dev** [comment]
What version of OSX are you using? Also please try running the bittube-wallet-gui binary from therminal and post the results.

**Comment by sthewissen** [comment]
I'm running High Sierra 10.13.5. Also the above error I get when I run the app through the terminal using:

```
open ./bittube-wallet-gui.app
```

**Comment by ipbc-dev** [comment]
run the binary inside the App.
`./Applications/bittube-wallet-gui.app/Contents/MacOS/bittube-wallet-gui`

**Comment by sthewissen** [comment]
When I run that I get a Permission Denied message. I am administrator on my PC, so that is kind of strange to me.

**Comment by ipbc-dev** [comment]
Download the 2.0.0.2 release again please. We updated the release yesterday because the binaries inside the app werent marked as executable. That would explain why the 2.0.0.1 worked for you.

**Comment by sthewissen** [comment]
It works, thanks!
