### ISSUE TITLE
Missing libpcsclite on ubuntu 18.04

### ISSUE THREAD

**Issue by fenicks** [ipbc-dev/bittube-wallet-gui#20]
Hi,
I'm running on Ubuntu 18.04 after installing the needed packages for Ubuntu 17.04+ the libpcsclite is missing.
This command helps : 

`sudo apt install libpcsclite-dev`

[Output error]
```bash
-- Checking for module 'libpcsclite'
--   No package 'libpcsclite' found
```

**Comment by italocoin-project** [comment]
Did you removed the build folder after you installed the library?
