### ISSUE TITLE
Sending Transaction Stalls

### ISSUE THREAD

**Issue by innout** [ipbc-dev/bittube-wallet-gui#22]
Tried to send 2 TUBE to my Bit.Tube Web Wallet as a test, but the "Creating Transaction" box sits (stalls) with the circling icon. I'm using the macOS v.2.0.0.2-13-ga51f190 (Qt 5.71) [Embedded BitTube Version 2.0.0.3] GUI wallet since I can't use the latest GUI v.2.0.0.4 since it is only for High Sierra (macOS 10.13). Will it be possible to make a Sierra (macOS 10.12) version of the latest GUI v.2.0.0.4 wallet? Or, fix the problem with the v.2.0.0.3? 

Network status 
Remote node
Wallet is synchronized
Daemon is synchronized (163009)

Checked the log and got this  message:  
2018-09-14 05:01:07.549	     0x10d0ec3c0	ERROR	frontend	src/wallet/api/wallet.cpp:366	Can't create transaction:  no connection to daemon. Please make sure daemon is running.

Checked the bittube.log and saw this message:
2018-09-14 06:47:35.004	     0x11113a3c0	ERROR	msgwriter	src/common/scoped_message_writer.h:103	Error: Couldn't connect to daemon: 127.0.0.1:24182

Don't know why it says that since everything is synced.

**Comment by ucybucy** [comment]
Hello, I am experiencing exactly the same problem. Have you already found the solution, please?

**Comment by innout** [comment]
No, I have not. I researched for information for days, but cannot find a solution. I’m hoping the Developers will read my GitHub comment and fix the problem with the wallet.

**Comment by ucybucy** [comment]
Ok, got it, thanks. Have you tried to make the transfer using remote or
local node?

niedz., 16 wrz 2018 o 19:35 innout <notifications@github.com> napisał(a):

**Comment by innout** [comment]
Tried to sync with local node, but could only get 90% synced and it would not finish syncing. Saved my wallet.dat, then deleted everything and used remote node which fully synced. Still am not able to send any transactions. Coins are stuck inside wallet.

**Comment by darksky101** [comment]
Hi.i have a problem to.i cant sent my tube in my GUI WALLET to bittrex its wallet is synchronized daemon is synchronized (166068)
I got my address and payment i.d signed up but i cant press the send button..can somebody help me.

**Comment by italocoin-project** [comment]
Please try latest release. Let me know if you still have the issue

**Comment by innout** [comment]
Thank you very much! the macOS Bittube 2.1.0.0 wallet works on macOS Sierra 10.12.6. Great job!

**Comment by italocoin-project** [comment]
Glad to hear all works well, can you please close the issue?

**Comment by innout** [comment]
Done. Thanks again!
