### ISSUE TITLE
Source fails to build and pre-build will never start

### ISSUE THREAD

**Issue by IronDusts** [ipbc-dev/bittube-wallet-gui#23]
Hello,

First tried running the pre-build binary. It complained about lots of old version libraries.
After some linking I made it to the point where it complained about libssl.1.0.0 
I'll write it again: libssl1.0.0
And again! libssl1.0.0  !!?!!! Is this a #$@%$in joke?!?!!! 
Nobody should ever use such old version of libssl. It's neither supported or secured. 
Even with some old compatible libraries couldn't make it start. 

When trying to build it spend about half day and couldn't get further than this:

 /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_DaemonManager.o moc_DaemonManager.cpp
g++ -fstack-protector -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -Wl,-O1 -o release/bin/bittube-wallet-gui main.o filter.o clipboardAdapter.o oscursor.o WalletManager.o Wallet.o PendingTransaction.o TransactionHistory.o TransactionInfo.o QRCodeImageProvider.o oshelper.o TranslationManager.o TransactionHistoryModel.o TransactionHistorySortFilterModel.o BitBuffer.o QrCode.o QrSegment.o AddressBookModel.o AddressBook.o SubaddressModel.o Subaddress.o zxcvbn.o UnsignedTransaction.o httpservice.o minermanager.o Logger.o MainApp.o DaemonManager.o qrc_translations.o qrc_qml.o moc_filter.o moc_clipboardAdapter.o moc_oscursor.o moc_WalletManager.o moc_Wallet.o moc_PendingTransaction.o moc_TransactionHistory.o moc_TransactionInfo.o moc_Transfer.o moc_NetworkType.o moc_oshelper.o moc_TranslationManager.o moc_TransactionHistoryModel.o moc_TransactionHistorySortFilterModel.o moc_AddressBookModel.o moc_AddressBook.o moc_SubaddressModel.o moc_Subaddress.o moc_UnsignedTransaction.o moc_httpservice.o moc_minermanager.o moc_MainApp.o moc_DaemonManager.o   -L/home/k_georgiev/bittube/bittube-wallet-gui/bittube/lib -lwallet_merged -lepee -lunbound -leasylogging -ldl -lboost_serialization -lboost_thread -lboost_system -lboost_date_time -lboost_filesystem -lboost_regex -lboost_chrono -lboost_program_options -lssl -llmdb -lcrypto -Wl,-Bdynamic -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld: cannot find -lwallet_merged
/usr/bin/ld: cannot find -lepee
/usr/bin/ld: cannot find -lunbound
/usr/bin/ld: cannot find -leasylogging
/usr/bin/ld: cannot find -llmdb
collect2: error: ld returned 1 exit status
make: *** [Makefile:385: release/bin/bittube-wallet-gui] Error 1
[k_georgiev@localhost bittube-wallet-gui]$ 

Google search said that I should install gcc/g++ version 5. Tried it and didn't work. 
No matter what development tools and libraries I installed couldn't make it work.

**Comment by italocoin-project** [comment]
Got fixed in latest release

+resolved
