### ISSUE TITLE
Build fails under Ubuntu 18.04

### ISSUE THREAD

**Issue by zcopley** [ipbc-dev/bittube-wallet-gui#24]
Any ideas?

``zcopley@chupa:~/bittube-wallet-gui$ ./build.sh 
Building release
~/bittube-wallet-gui ~/bittube-wallet-gui
./build.sh: line 75: ./get_libwallet_api.sh: Permission denied
make: Entering directory '/home/zcopley/bittube-wallet-gui/src/zxcvbn-c'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/zcopley/bittube-wallet-gui/src/zxcvbn-c'
You are currently on commit 56b04d6
The most recent tag was at 63e5ed9
You are ahead of or behind a tagged release
~/bittube-wallet-gui/bittube ~/bittube-wallet-gui ~/bittube-wallet-gui
You are currently on commit 0d053d86
The most recent tag was at 0c6d50f0
You are ahead of or behind a tagged release
~/bittube-wallet-gui ~/bittube-wallet-gui
Project MESSAGE: Building without libunwind
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ar.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ar.qm'...
    Generated 257 translation(s) (257 finished and 0 unfinished)
    Ignored 207 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cat.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cat.qm'...
    Generated 241 translation(s) (241 finished and 0 unfinished)
    Ignored 166 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cs.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cs.qm'...
    Generated 476 translation(s) (476 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_da.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_da.qm'...
    Generated 442 translation(s) (442 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_de.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_de.qm'...
    Generated 483 translation(s) (483 finished and 0 unfinished)
    Ignored 21 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_eo.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_eo.qm'...
    Generated 479 translation(s) (479 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_es.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_es.qm'...
    Generated 480 translation(s) (480 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fi.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fi.qm'...
    Generated 126 translation(s) (126 finished and 0 unfinished)
    Ignored 315 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fr.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_he.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_he.qm'...
    Generated 467 translation(s) (467 finished and 0 unfinished)
    Ignored 20 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hi.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hi.qm'...
    Generated 49 translation(s) (49 finished and 0 unfinished)
    Ignored 424 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hr.qm'...
    Generated 365 translation(s) (365 finished and 0 unfinished)
    Ignored 104 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_id.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_id.qm'...
    Generated 257 translation(s) (257 finished and 0 unfinished)
    Ignored 194 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_it.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_it.qm'...
    Generated 466 translation(s) (466 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ja.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ja.qm'...
    Generated 480 translation(s) (480 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ko.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ko.qm'...
    Generated 276 translation(s) (276 finished and 0 unfinished)
    Ignored 170 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_nl.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_nl.qm'...
    Generated 478 translation(s) (478 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pl.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pl.qm'...
    Generated 476 translation(s) (476 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-br.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-br.qm'...
    Generated 472 translation(s) (472 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-pt.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-pt.qm'...
    Generated 464 translation(s) (464 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ro.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ro.qm'...
    Generated 466 translation(s) (466 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ru.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ru.qm'...
    Generated 479 translation(s) (479 finished and 0 unfinished)
    Ignored 12 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sk.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sk.qm'...
    Generated 439 translation(s) (439 finished and 0 unfinished)
    Ignored 33 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sl.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sl.qm'...
    Generated 318 translation(s) (318 finished and 0 unfinished)
    Ignored 132 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sr.qm'...
    Generated 461 translation(s) (461 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sv.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sv.qm'...
    Generated 468 translation(s) (468 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_tr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_tr.qm'...
    Generated 472 translation(s) (472 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ua.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ua.qm'...
    Generated 369 translation(s) (369 finished and 0 unfinished)
    Ignored 114 untranslated source text(s)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-cn.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-cn.qm'...
    Generated 478 translation(s) (478 finished and 0 unfinished)
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-tw.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-tw.qm'...
    Generated 481 translation(s) (481 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_ar.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ar.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ar.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ar.qm'...
    Generated 257 translation(s) (257 finished and 0 unfinished)
    Ignored 207 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_cat.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cat.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cat.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cat.qm'...
    Generated 241 translation(s) (241 finished and 0 unfinished)
    Ignored 166 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_cs.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cs.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cs.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_cs.qm'...
    Generated 476 translation(s) (476 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_da.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_da.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_da.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_da.qm'...
    Generated 442 translation(s) (442 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_de.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_de.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_de.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_de.qm'...
    Generated 483 translation(s) (483 finished and 0 unfinished)
    Ignored 21 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_eo.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_eo.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_eo.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_eo.qm'...
    Generated 479 translation(s) (479 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_es.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_es.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_es.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_es.qm'...
    Generated 480 translation(s) (480 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_fi.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fi.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fi.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fi.qm'...
    Generated 126 translation(s) (126 finished and 0 unfinished)
    Ignored 315 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_fr.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fr.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_fr.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_he.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_he.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_he.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_he.qm'...
    Generated 467 translation(s) (467 finished and 0 unfinished)
    Ignored 20 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_hi.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hi.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hi.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hi.qm'...
    Generated 49 translation(s) (49 finished and 0 unfinished)
    Ignored 424 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_hr.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hr.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_hr.qm'...
    Generated 365 translation(s) (365 finished and 0 unfinished)
    Ignored 104 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_id.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_id.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_id.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_id.qm'...
    Generated 257 translation(s) (257 finished and 0 unfinished)
    Ignored 194 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_it.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_it.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_it.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_it.qm'...
    Generated 466 translation(s) (466 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_ja.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ja.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ja.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ja.qm'...
    Generated 480 translation(s) (480 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_ko.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ko.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ko.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ko.qm'...
    Generated 276 translation(s) (276 finished and 0 unfinished)
    Ignored 170 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_nl.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_nl.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_nl.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_nl.qm'...
    Generated 478 translation(s) (478 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_pl.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pl.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pl.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pl.qm'...
    Generated 476 translation(s) (476 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_pt-br.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-br.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-br.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-br.qm'...
    Generated 472 translation(s) (472 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_pt-pt.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-pt.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-pt.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_pt-pt.qm'...
    Generated 464 translation(s) (464 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_ro.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ro.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ro.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ro.qm'...
    Generated 466 translation(s) (466 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_ru.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ru.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ru.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ru.qm'...
    Generated 479 translation(s) (479 finished and 0 unfinished)
    Ignored 12 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_sk.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sk.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sk.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sk.qm'...
    Generated 439 translation(s) (439 finished and 0 unfinished)
    Ignored 33 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_sl.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sl.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sl.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sl.qm'...
    Generated 318 translation(s) (318 finished and 0 unfinished)
    Ignored 132 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_sr.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sr.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sr.qm'...
    Generated 461 translation(s) (461 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_sv.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sv.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sv.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_sv.qm'...
    Generated 468 translation(s) (468 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_tr.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_tr.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_tr.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_tr.qm'...
    Generated 472 translation(s) (472 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_ua.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ua.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ua.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_ua.qm'...
    Generated 369 translation(s) (369 finished and 0 unfinished)
    Ignored 114 untranslated source text(s)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_zh-cn.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-cn.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-cn.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-cn.qm'...
    Generated 478 translation(s) (478 finished and 0 unfinished)
/usr/lib/qt5/bin/lrelease -compress -nounfinished -removeidentical ../translations/bittube-core_zh-tw.ts -qm /home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-tw.qm
Updating '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-tw.qm'...
Removing translations equal to source text in '/home/zcopley/bittube-wallet-gui/build/translations/bittube-core_zh-tw.qm'...
    Generated 481 translation(s) (481 finished and 0 unfinished)
/usr/lib/qt5/bin/rcc -name translations translations/translations.qrc -o qrc_translations.cpp
g++ -c -pipe -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -O2 -std=gnu++11 -pthread -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../bittube-wallet-gui -I. -I../bittube/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -I../bittube/src -isystem /usr/include/PCSC -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o qrc_translations.o qrc_translations.cpp
/usr/lib/qt5/bin/rcc -name qml ../qml.qrc -o qrc_qml.cpp
g++ -c -pipe -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -O2 -std=gnu++11 -pthread -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../bittube-wallet-gui -I. -I../bittube/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -I../bittube/src -isystem /usr/include/PCSC -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o qrc_qml.o qrc_qml.cpp
g++ -fstack-protector -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -Wl,-O1 -o release/bin/bittube-wallet-gui main.o filter.o clipboardAdapter.o oscursor.o WalletManager.o Wallet.o PendingTransaction.o TransactionHistory.o TransactionInfo.o QRCodeImageProvider.o oshelper.o TranslationManager.o TransactionHistoryModel.o TransactionHistorySortFilterModel.o BitBuffer.o QrCode.o QrSegment.o AddressBookModel.o AddressBook.o SubaddressModel.o Subaddress.o zxcvbn.o UnsignedTransaction.o httpservice.o minermanager.o Logger.o MainApp.o DaemonManager.o qrc_translations.o qrc_qml.o moc_filter.o moc_clipboardAdapter.o moc_oscursor.o moc_WalletManager.o moc_Wallet.o moc_PendingTransaction.o moc_TransactionHistory.o moc_TransactionInfo.o moc_Transfer.o moc_NetworkType.o moc_oshelper.o moc_TranslationManager.o moc_TransactionHistoryModel.o moc_TransactionHistorySortFilterModel.o moc_AddressBookModel.o moc_AddressBook.o moc_SubaddressModel.o moc_Subaddress.o moc_UnsignedTransaction.o moc_httpservice.o moc_minermanager.o moc_MainApp.o moc_DaemonManager.o   -L/home/zcopley/bittube-wallet-gui/bittube/lib -lwallet_merged -lepee -lunbound -leasylogging -ldl -lboost_serialization -lboost_thread -lboost_system -lboost_date_time -lboost_filesystem -lboost_regex -lboost_chrono -lboost_program_options -lssl -llmdb -lcrypto -Wl,-Bdynamic -lpcsclite -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/x86_64-linux-gnu-ld: cannot find -lwallet_merged
/usr/bin/x86_64-linux-gnu-ld: cannot find -lepee
/usr/bin/x86_64-linux-gnu-ld: cannot find -leasylogging
/usr/bin/x86_64-linux-gnu-ld: cannot find -llmdb
collect2: error: ld returned 1 exit status
Makefile:307: recipe for target 'release/bin/bittube-wallet-gui' failed

**Comment by zcopley** [comment]
If anyone else is having trouble I figure out the problem.

All of the Bash shell scripts in the bittube-wallet-gui directory need to be executable before you run build.sh. You also need to pull down the git submodules before building.

```
# git clone https://github.com/ipbc-dev/bittube-wallet-gui.git
# cd bittube-wallet-gui/
# git submodule update --init --recursive
# chmod 755 *.sh
# ./buld.sh
```

**Comment by alexspirin** [comment]
second line should have \ before ;

**Comment by zcopley** [comment]
> second line should have \ before ;

Thanks! Fixed.
