### ISSUE TITLE
[Improvement] "Dont ask again" if I want to stop the Daemon

### ISSUE THREAD

**Issue by Neoony** [ipbc-dev/bittube-wallet-gui#3]
[Improvement]
Add an option of "Dont ask again" if I want to close the daemon, when Iam closing the wallet.
Also for when I wanna always keep it running.

![](https://i.imgur.com/DT97zYM.png)

Also.
There should be an explanation about what it means to keep it running, or to close it.

**Comment by italocoin-project** [comment]
We will work on that in the future, about the explanation you have the explanation there, the daemon will keep running if you don;t stop it!

![image](https://user-images.githubusercontent.com/12392580/52535766-990f5d80-2d52-11e9-93ea-9a9f6fe6b424.png)
