### ISSUE TITLE
Unable to quit latest version 2.1.0.2 wallet normally.

### ISSUE THREAD

**Issue by innout** [ipbc-dev/bittube-wallet-gui#36]
Using the latest version 2.1.0.2 on macOS 10.12.6 (Sierra) and am unable to quit the wallet normally. Selecting "Quit" from menu bar, CMD-Q from keyboard, and clicking the "X" in the upper right corner of the wallet window all do not work to quit the wallet.

Edit:  Got tired of waiting for the fix, so upgraded my OS and installed version 3.0.0.0.

**Comment by breadsax** [comment]
@innout I believe this happens when using Qt version 5.12 (same issue with Monero GUI). I wonder if the devs compiled and packaged the macOS build with that Qt version. It should work correctly if compiled using Qt 5.11

**Comment by ipbc-dev** [comment]
let me check, as far i know it is 5.12QT
