### ISSUE TITLE
Missing dependency for Ubuntu 18.04.4 and bittube-wallet-gui 3.0.0

### ISSUE THREAD

**Issue by zcopley** [ipbc-dev/bittube-wallet-gui#38]
Even after installing all of the dependencies following the build instructions I received this error when trying to build on Ubuntu 18.04.04 LTS:

> ERROR: Unknown module(s) in QT: svg

Fixed it with:

> sudo apt-get install libqt5svg5*

**Comment by ipbc-dev** [comment]
ty
