### ISSUE TITLE
Project ERROR: Can't build with Qt 5.5.1. Use at least Qt 5.7.0

### ISSUE THREAD

**Issue by lexandr0s** [ipbc-dev/bittube-wallet-gui#6]
Error at the beginning of the build
Ubuntu 16.04

**Comment by ipbc-dev** [comment]
Please check the readme. Qt 5.7 is the minimum version required to build the GUI. This makes some distributions (mostly based on debian, like Ubuntu 16.x or Linux Mint 18.x) obsolete. You can still build the GUI if you install an official Qt release, but this is not officially supported.
