### ISSUE TITLE
Precompiled wallet not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by lexandr0s** [ipbc-dev/bittube-wallet-gui#7]
./bittubed: error while loading shared libraries: libboost_chrono.so.1.62.0: cannot open shared object file: No such file or directory

libboost_chrono.so.1.62.0 from zesty repo???

**Comment by yair** [comment]
And source won't compile due to #6 . Did you find a way to run it on 16.04?

**Comment by somhi** [comment]
The same in Ubuntu 18.04

**Comment by alexspirin** [comment]
Same on 18.04
There is no application installed for shared library files.

**Comment by italocoin-project** [comment]
This should be fixed by now! Download latest release

+resolved
