### ISSUE TITLE
Daemon ends himself

### ISSUE THREAD

**Issue by fuezi84** [ipbc-dev/bittube-wallet-gui#8]
Daemon stores in an incorrectly named profile if the windows user profil has the letter ü,ö,ä inside the name!

**Comment by italocoin-project** [comment]
Can i have the log file?

**Comment by fuezi84** [comment]
Sorry its to long ago!
I have reinstall my system and now my windows user name haven't a
letter with diacritic, so i have no troubles anymore!

Italocoin Project <notifications@github.com> schrieb am So., 10. Feb. 2019,
16:43:
