### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by N0ir** [ipbc-dev/bittube-wallet-gui#9]
Why is windows defender saying there is a trojan -- Sirefef.gen!C ?
Got the latest version: 2.0.0.1

**Comment by ipbc-dev** [comment]
Please check again with the 2.0.0.2 release.

**Comment by Neoony** [comment]
Comodo Internet Security Premium **now fine** with wallet _2.0.0.3_  
[was .UnclassifiedMalware@1 with 2.0.0.1]
